fixtures:
  repositories:
    registry: git://github.com/puppetlabs/puppetlabs-registry.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    windows_autologin: "#{source_dir}"
